models/player.py
from models.base import Base
from models.city import City
from database import db


class Player(Base):
    __tablename__ = 'player'

    name = db.Column(db.String(80), nullable=False)
    id = db.Column(db.Integer, primary_key=True)
    sport = db.Column(db.String(250))
    height = db.Column(db.Integer)  # in cm
    weight = db.Column(db.Integer)  # in kg
    city_id = db.Column(db.Integer, db.ForeignKey('city.id'))
    city = db.relationship(City)

    def __init__(self, name, height, weight, sport, city_id):
        self.name = name
        self.height = height
        self.weight     = weight
        self.sport = sport
        self.city_id = city_id

    @property
    def serialize(self):
        return {
            'name': self.name,
            'id': self.id,
            'height': self.height,
            'weight': self.weight,
            'sport': self.sport,
        }

    @classmethod
    def find_all_players(cls, city_id):
        return cls.query.filter_by(city_id=city_id).all()

    @classmethod
    def find_by_id(cls, player_id):
        return cls.query.filter_by(id=player_id).first()

controllers/city.py
from flask import render_template, redirect, request, url_for, flash, Blueprint

from models.city import City
from models.user import User
from .user import login_session


city_url = Blueprint('city_url', __name__)


# show all cities
@city_url.route('/')
@city_url.route('/city/')
def show_cities():
    cities = City.find_all_cities()
    if 'username' not in login_session:
        return render_template('public_cities.html', cities=cities)
    else:
        viewer = User.get_user_info(login_session.get('email'))
        return render_template('cities.html', cities=cities, viewer=viewer)


# Add a new City
@city_url.route('/city/new/', methods=['GET', 'POST'])
def new_city():
    if 'username' not in login_session:
        return redirect('/login')
    if request.method == 'POST':
        new_city = City(name=request.form['name'], user_id=login_session['user_id'])
        if new_city.name == '':
            flash('Please enter a city before submitting') # flash if the field is empty
            return render_template('new_city.html')
        new_city.save_to_db()
        flash('New City %s Successfully Created' % new_city.name)
        return redirect(url_for('city_url.show_cities'))
    else:
        return render_template('new_city.html')


# Edit a City
@city_url.route('/city/<int:city_id>/edit', methods=['GET', 'POST'])
def edit_city(city_id):
    if 'username' not in login_session:
        return redirect('/login')
    edited_city = City.find_by_id(city_id)
    if edited_city.user_id != login_session['user_id']:
        flash('You are not authorized to edit the the city.')
        return redirect(url_for('city_url.show_cities'))
    if request.method == 'POST':
        if request.form['name']:
            edited_city.name = request.form['name']
            edited_city.save_to_db()
            flash('City Successfully Edited %s' % edited_city.name)
            return redirect(url_for('city_url.show_cities'))
        flash('Please enter a city before submitting')  # flash if the field is empty
        return render_template('edit_city.html', city=edited_city)
    else:
        return render_template('edit_city.html', city=edited_city)


# Delete a City
@city_url.route('/city/<int:city_id>/delete/', methods=['GET', 'POST'])
def delete_city(city_id):
    city_to_delete = City.find_by_id(city_id)
    if 'username' not in login_session:
        return redirect('/login')
    if city_to_delete.user_id != login_session['user_id']:
        flash('You are not authorized to delete the city.')
        return redirect(url_for('city_url.show_cities'))
    if request.method == 'POST':
        city_to_delete.delete_from_db()
        flash('%s Successfully Deleted' % city_to_delete.name)
        return redirect(url_for('city_url.show_cities', city_id=city_id))
    else:
        return render_template('delete_city.html', city=city_to_delete)

controllers/player.py
from flask import Blueprint, render_template, redirect, request, url_for, flash
from flask import session as login_session

from models.city import City
from models.player import Player

player_url = Blueprint('player_url', __name__)


@player_url.route('/city/<int:city_id>/')
@player_url.route('/city/<int:city_id>/players/')
def show_players(city_id):
    city = City.find_by_id(city_id)
    players = Player.find_all_players(city_id)
    if 'username' not in login_session:
        return render_template('public_players.html', players=players, city=city)
    else:
        return render_template('players.html', players=players, city=city)


# Add a new Player to the city
@player_url.route('/city/<int:city_id>/players/new/', methods=['GET', 'POST'])
def new_player(city_id):
    if 'username' not in login_session:
        return redirect('/login')
    city = City.find_by_id(city_id)
    if city.user_id != login_session['user_id']:
        flash('You are not authorized to add new players to the city')
        return redirect(url_for('player_url.show_players', city_id=city_id))
    if request.method == 'POST':
        new_player_figure = Player(name=request.form['name'], height=request.form[
                           'height'], weight=request.form['weight'], sport=request.form['sport'], city_id=city_id)
        if new_player_figure.name == '':
            flash('Please enter a name before submitting') # flash if the field is empty
            return render_template('new_player.html', city_id=city_id)
        new_player_figure.save_to_db()
        flash('New Player %s Successfully Created' % (new_player_figure.name))
        return redirect(url_for('player_url.show_players', city_id=city_id))
    else:
        return render_template('new_player.html', city_id=city_id)


# Edit player from different players
@player_url.route('/city/<int:city_id>/players/<int:player_id>/edit', methods=['GET', 'POST'])
def edit_player(city_id, player_id):
    if 'username' not in login_session:
        return redirect('/login')
    city = City.find_by_id(city_id)
    if city.user_id != login_session['user_id']:
        flash('You are not authorized to edit players in the city')
        return redirect(url_for('player_url.show_players', city_id=city_id))
    edited_player_figure = Player.find_by_id(player_id)
    if request.method == 'POST':
        if request.form['name']:
            edited_player_figure.name = request.form['name']
        if request.form['height']:
            edited_player_figure.height = request.form['height']
        if request.form['weight']:
            edited_player_figure.weight = request.form['weight']
        if request.form['sport']:
            edited_player_figure.sport = request.form['sport']
        edited_player_figure.save_to_db()
        flash('Player Successfully Edited')
        return redirect(url_for('player_url.show_players', city_id=city_id))
    else:
        return render_template('edit_player.html', city_id=city_id, player_id=player_id, player=edited_player_figure)


# Delete players
@player_url.route('/city/<int:city_id>/players/<int:player_id>/delete', methods=['GET', 'POST'])
def delete_player(city_id, player_id):
    if 'username' not in login_session:
        return redirect('/login')
    city = City.find_by_id(city_id)
    if city.user_id != login_session['user_id']:
        flash('You are not authorized to delete players in the city')
        return redirect(url_for('player_url.show_players', city_id=city_id))
    player_to_delete = Player.find_by_id(player_id)
    if request.method == 'POST':
        player_to_delete.delete_from_db()
        flash('Player Successfully Deleted')
        return redirect(url_for('player_url.show_players', city_id=city_id))
    else:
        return render_template('delete_player.html', player=player_to_delete)

controllers/user.py
import json
import random
import string
import httplib2
import requests

from flask import Blueprint, render_template, request, redirect, url_for, flash, make_response
from flask import session as login_session
from oauth2client.client import FlowExchangeError
from oauth2client.client import flow_from_clientsecrets

from models.user import User


user_url = Blueprint('user_url', __name__)


CLIENT_ID = json.loads(
    open('client_secrets.json', 'r').read())['web']['client_id']
APPLICATION_NAME = "Player team Application"


# Helper functions
def create_user(login_session):
    new_user = User(name=login_session['username'], email=login_session[
                       'email'], picture=login_session['picture'])
    new_user.save_to_db()
    return new_user.id


@user_url.route('/login')
def show_login():
    state = ''.join(random.choice(string.ascii_uppercase + string.digits)
                    for x in xrange(32))
    login_session['state'] = state
    return render_template('login.html', STATE=state)


@user_url.route('/gconnect', methods=['POST'])
def gconnect():
    if request.args.get('state') != login_session['state']: # compares the state token passed in with the login session
        response = make_response(json.dumps('Invalid state parameter'), 401)
        response.headers['Content-Type'] = 'application/json'
        return response
    code = request.data # one time code

    try:
        oauth_flow = flow_from_clientsecrets('client_secrets.json', scope='')
        oauth_flow.redirect_uri = 'postmessage'
        credentials = oauth_flow.step2_exchange(code) # collects the access token with the one time code
    except FlowExchangeError:
        response = make_response(json.dumps('Failed to upgrade the ' +
                                            'authorization code'), 401)
        response.headers['Content-Type'] = 'application/json'
        return response # send the response as a json object

    # Check that the access token is valid
    access_token = credentials.access_token
    login_session['access_token'] = credentials.access_token
    url = 'https://www.googleapis.com/oauth2/v1/tokeninfo?access_token=%s' % access_token #appends  the tken to URL

    http = httplib2.Http()
    result = json.loads(http.request(url, 'GET')[1]) #json get request
    # If there is an error in the access token info, abort
    if result.get('error') is not None:
        response = make_response(json.dumps(result.get('error')), 500)
        response.headers['Content-Type'] = 'application/json'

    # Verify that the access token is used for the intended user
    gplus_id = credentials.id_token['sub']
    if result['user_id'] != gplus_id:
        response = make_response(
            json.dumps("Token's user ID doesn't match given user ID."), 401)
        response.headers['Content-Type'] = 'application/json'
        return response

    # Verify that the access token is valid for this app.
    if result['issued_to'] != CLIENT_ID:
        response = make_response(
            json.dumps("Token's client ID does not match app's."), 401)
        response.headers['Content-Type'] = 'application/json'
        return response

    stored_credentials = login_session.get('credentials')
    stored_gplus_id = login_session.get('gplus_id')
    if stored_credentials is not None and gplus_id == stored_gplus_id:
        response = make_response(json.dumps('Current user is already connected.'),
                                 200)
        response.headers['Content-Type'] = 'application/json'
        return response

    # Store the access token in the session for later use.
    login_session['credentials'] = credentials.access_token
    login_session['gplus_id'] = gplus_id

    # Get user info
    userinfo_url = "https://www.googleapis.com/oauth2/v2/userinfo"
    params = {'access_token': credentials.access_token, 'alt': 'json'}
    answer = requests.get(userinfo_url, params=params)

    data = answer.json()

    login_session['username'] = data['name']
    login_session['picture'] = data['picture']
    login_session['email'] = data['email']

    user_id = User.get_user_id(login_session['email'])
    if not user_id:
        user_id = create_user(login_session)
    login_session['user_id'] = user_id

    return render_template('connecting.html', login_session=login_session)


@user_url.route('/gdisconnect', methods=['GET', 'POST'])
def gdisconnect():
    access_token = login_session.get('access_token')
    if access_token is None:
        response = make_response(json.dumps('Current user not connected.'), 401)
        response.headers['Content-Type'] = 'application/json'
        return response
    url = 'https://accounts.google.com/o/oauth2/revoke?token=%s' % access_token
    h = httplib2.Http()
    result = h.request(url, 'GET')[0]
    if result['status'] == '200':
        del login_session['credentials']
        del login_session['gplus_id']
        del login_session['username']
        del login_session['email']
        del login_session['picture']
        del login_session['user_id']
        response = make_response(json.dumps('Successfully disconnected.'), 200)
        response.headers['Content-Type'] = 'application/json'
        flash("you have signed out!")
        return redirect(url_for('city_url.show_cities'))
    else:
        response = make_response(json.dumps('Failed to revoke token for given user.', 400))
        response.headers['Content-Type'] = 'application/json'
        return response

templates/cities.html
{% extends "main.html" %}
{% block content %}
{% include "header.html" %}
	<div class="row top-teams">
		<div class="col-md-10"></div>
		<div class="col-md-2 text-right">
					</div>
	</div>
	<div class="row divider blue">
		<div class="col-md-12"></div>
	</div>
	<div class="row banner main">
		<div class="col-md-1"></div>
		<div class="col-md-11 padding-none">
			<h1>Cities</h1>
		</div>
	</div>

<div class = 'flash'>
		      {% with messages = get_flashed_messages() %}
      {% if messages %}
          
        <ul>
        {% for message in messages %}
            <li> <strong> {{ message }} </strong> </li>
        {% endfor %}
        </ul>
        {% endif %}
    {% endwith %}

</div>
	
	<div class="row padding-top padding-bottom">
		<div class="col-md-1"></div>
		<div class="col-md-10 padding-none">
			<a href="{{url_for('city_url.new_city')}}">
				<button class="btn btn-default" id="new-city">
					<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>Add City
				</button>
			</a>
		</div>
		<div class="col-md-1"></div>
	</div>
	{% for city in cities %}
		<a href = "{{url_for('player_url.show_players', city_id = city.id)}}">
			<div class="row">
				<div class="col-md-1"></div>
					<div class="col-md-10 city-list">
						<h3>{{city.name}}</h3>
                        {% if city.user_id == viewer.id %}
                        <strong> Created by {{viewer.name}} </strong>
                        {% endif %}
					</div>
				<div class="col-md-1"></div>
			</div>
		</a>
	{% endfor %}
{% endblock %}

templates/connecting.html
<h1>Welcome {{login_session['username']}} 
	<br>
	<img src="{{login_session['picture']}}"" style = "width: 300px; height: 300px;border-radius: 150px;">
	<br>
	you are now logged in as {{login_session['username']}}
	done!
</h1>

templates/delete_city.html
{% extends "main.html" %}
{% block content %}
{% include "header.html" %}
<h2> Are you sure you want to delete {{city.name}}? </h2>

<form action="#" method = 'post'>

	<button type="submit" class="btn btn-default delete" id="submit" type="submit">
	<span class="glyphicon glyphicon-trash" aria-hidden="true"></span>Delete</button>
	<a href = '{{url_for('city_url.show_cities')}}'>
		<button class="btn btn-default delete">
		<span class="glyphicon glyphicon-remove" aria-hidden="true"></span> Cancel</button>
	</a>

</form>

{% endblock %}

templates/delete_player.html
{% extends "main.html" %}
{% block content %}
{% include "header.html" %}
<h2> Are you sure you want to delete {{player.name}}? </h2>

<form action="#" method = 'post'>

	<button type="submit" class="btn btn-default delete" id="submit" type="submit">
	<span class="glyphicon glyphicon-trash" aria-hidden="true"></span>Delete</button>
	<a href = '{{url_for('city_url.show_cities')}}'>
		<button class="btn btn-default delete">
		<span class="glyphicon glyphicon-remove" aria-hidden="true"></span> Cancel</button>
	</a>

</form>

{% endblock %}

templates/edit_city.html
{% extends "main.html" %}
{% block content %}
{% include "header.html" %}
	<div class="row divider green">
		<div class="col-md-12"></div>
	</div>
	<div class="row banner player">
		<div class="col-md-11 col-md-offset-1 padding-none">
			<h1>Edit {{city.name}}</h1>
		</div>
	</div>
    <div class = 'flash'>
            {% with messages = get_flashed_messages() %}
      {% if messages %}

        <ul>
        {% for message in messages %}
            <li> <strong> {{ message }} </strong> </li>
        {% endfor %}
        </ul>
        {% endif %}
    {% endwith %}
    </div>
	<div class="row">
		<div class="col-md-6 col-md-offset-1 padding-top">
			<form action="{{ url_for('city_url.edit_city',city_id = city.id)}}" method = "post">
				<div class="form-group">
					<label for="name">Name:</label>
					<input type ="text" class="form-control" name="name" value="{{city.name }}">
					<div class="padding-bottom"></div>
					<button type="submit" class="btn btn-default" id="submit" type="submit">
					<span class="glyphicon glyphicon-ok" aria-hidden="true"></span>Save</button>
					<a href = '{{url_for('city_url.show_cities')}}'>
						<button class="btn btn-default delete">
						<span class="glyphicon glyphicon-remove" aria-hidden="true"></span> Cancel</button>
					</a>
				</div>
			</form>
		</div>
	</div>
{% endblock %}

templates/edit_player.html
{% extends "main.html" %}
{% block content %}
{% include "header.html" %}
	<div class="row divider green">
		<div class="col-md-12"></div>
	</div>
	<div class="row banner teams">
		<div class="col-md-11 col-md-offset-1 padding-none">
			<h1>Edit Player</h1>
		</div>
	</div>
	<div class="row">
		<div class="col-md-6 col-md-offset-1 padding-top">
			<form action="#" method = "post">
				<div class="form-group">
					<label for="name">Name:</label>
					<input type ="text" maxlength="80" class="form-control" name="name" placeholder="Name of the Player">

					<label for="height">Height:</label>
					<input type ="text" maxlength="50" class="form-control" name="height" placeholder="Height of the Player in cm">

					<label for="weight">Weight:</label>
					<input type ="text" maxlength="50" class="form-control" name="weight" placeholder="Weight of the Player in kg">

					<label for="sport">Sport:</label>
					<div class="radio">
					  <label>
					    <input type="radio" name="sport" checked="checked" id="sport1" value="Basketball">Basketball
					  </label>
					</div>
					<div class="radio">
					  <label>
					    <input type="radio" name="sport" id="sport2" value="Football">Football
					  </label>
					</div>
					<div class="radio">
					  <label>
					    <input type="radio" name="sport" id="sport3" value="Hockey">Hockey
					  </label>
					</div>
				</div>
					<button type="submit" class="btn btn-default" id="submit" type="submit">
					<span class="glyphicon glyphicon-ok" aria-hidden="true"></span>Save</button>
					<a href = '{{url_for('city_url.show_cities')}}'>
						<button class="btn btn-default delete">
						<span class="glyphicon glyphicon-remove" aria-hidden="true"></span> Cancel</button>
					</a>
				</div>
			</form>
		</div>
	</div>
{% endblock %}

templates/header.html
<div class="row top-teams">
	<div class="col-md-6">
		<a href="{{url_for('city_url.show_cities')}}">
			<span class="glyphicon glyphicon-home" aria-hidden="true"></span>Show All Cities
		</a>
	</div>
	<div class="col-md-6 text-right">
					{%if 'username' not in session %}
			<a href="{{url_for('user_url.show_login')}}">Click Here to Login </a>
			{% else %}
			<a href="{{url_for('user_url.gdisconnect')}}">Logout </a>
			{% endif %}
		
	</div>
</div>

templates/login.html
<head>

  <!--LOAD PRE-REQUISITES FOR GOOGLE SIGN IN -->
   <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js">
  </script>

<script src="//apis.google.com/js/platform.js?onload=start"> </script>

<!-- END PRE-REQUISITES FOR GOOGLE SIGN IN -->


</head>


<body>  


<!-- GOOGLE PLUS SIGN IN-->

          
          <div id="signInButton">
          <span class="g-signin"
            data-scope="openid email"
            data-clientid="895799085360-q8i774kjpj3h6650ql0sko6f4rbsuf1v.apps.googleusercontent.com"
            data-redirecturi="postmessage"
            data-accesstype="offline"
            data-cookiepolicy="single_host_origin"
            data-callback="signInCallback"
            data-approvalprompt="force">
          </span>
        </div>

<div id="result"></div>

<script>
function signInCallback(authResult) {
  if (authResult['code']) {

    // Hide the sign-in button now that the user is authorized
    $('#signinButton').attr('style', 'display: none');

    // Send the one-time-use code to the server, if the server responds, write a 'login successful' message to the web page and then redirect back to the main cities page
    $.ajax({
      type: 'POST',
      url: '/gconnect?state={{STATE}}',
      processData: false,
      data: authResult['code'],
      contentType: 'application/octet-stream; charset=utf-8',
      success: function(result) {
        // Handle or verify the server response if necessary.
        if (result) {
          $('#result').html('Login Successful!</br>'+ result + '</br>Redirecting...')
         setTimeout(function() {
          window.location.href = "/city";
         }, 4000);
          

      } else if (authResult['error']) {

    console.log('There was an error: ' + authResult['error']);
  } else {
        $('#result').html('Failed to make a server-side call. Check your configuration and console.');
         }

      }
      
  }); } }
</script>







</script>

templates/main.html
<!DOCTYPE html>
<html lang="e`n">
	<head>
		<link href='http://fonts.googleapis.com/css?family=Roboto:400,300,700' rel='stylesheet' type='text/css'>
		<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
		<link rel=stylesheet type=text/css href="{{ url_for('static', filename='styles.css') }}">
	</head>
	<body>
		<div class="container">
			{% block content %}
			{% endblock %}
		</div>
	</body>
</html>

templates/new_city.html
{% extends "main.html" %}
{% block content %}
{% include "header.html" %}
	<div class="row divider green">
		<div class="col-md-12"></div>
	</div>
	<div class="row banner player">
		<div class="col-md-11 col-md-offset-1 padding-none">
			<h1>New City</h1>
		</div>
	</div>
    <div class = 'flash'>
		      {% with messages = get_flashed_messages() %}
      {% if messages %}

        <ul>
        {% for message in messages %}
            <li> <strong> {{ message }} </strong> </li>
        {% endfor %}
        </ul>
        {% endif %}
    {% endwith %}
    </div>
	<div class="row">
		<div class="col-md-6 col-md-offset-1 padding-top">
			<form action="#" method = "post">
				<div class="form-group">
				<label for="name">Name:</label>
				<input type ="text" class="form-control" maxlength="100" name="name">
				<div class="padding-bottom"></div>
				<button type="submit" class="btn btn-default" id="submit" type="submit">
				<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>Create</button>
				</div>
			</form>
		</div>
	</div>


{% endblock %}

templates/players.html
{% extends "main.html" %}
{% block content %}
{% include "header.html" %}
	<div class="row divider green">
		<div class="col-md-12"></div>
	</div>

<div class = 'flash'>
		      {% with messages = get_flashed_messages() %}
      {% if messages %}
          
        <ul>
        {% for message in messages %}
            <li> <strong> {{ message }} </strong> </li>
        {% endfor %}
        </ul>
        {% endif %}
    {% endwith %}

</div>
	<div class="row padding-top padding-bottom">
		<div class="col-md-1"></div>
		<div class="col-md-11 padding-none">
			<a href="{{url_for('city_url.edit_city', city_id = city.id )}}">
				<button class="btn btn-default" id="new-Player-item">
					<span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>Edit City
				</button>
			</a>
			<a href="{{url_for('player_url.new_player', city_id = city.id )}}">
				<button class="btn btn-default" id="new-player-item">
					<span class="glyphicon glyphicon-user" aria-hidden="true"></span>Add Player Item
				</button>
			</a>
						<a href="{{url_for('city_url.delete_city', city_id = city.id )}}">
				<button class="btn btn-default delete" id="delete-city">
					<span class="glyphicon glyphicon-trash" aria-hidden="true"></span>Delete City
				</button>
			</a>
		</div>
		<div class="col-md-7"></div>
	</div>
	
	{% if players !=[] %}	
		<div class="row">
			<div class="col-md-1"></div>
			<div class="col-md-3">
				<h2>Basketball</h2>
					{% for i in players %}
						{% if i.sport == 'Basketball' %}
							<div class="player-item">
								<h3>{{i.name}}</h3>
								<p>{{i.height}} cm</p>
								<p>{{i.weight}} kg</p>
								<a href='{{url_for('player_url.edit_player', city_id = city.id, player_id=i.id ) }}'>Edit</a> |
								<a href='{{url_for('player_url.delete_player', city_id = city.id, player_id=i.id ) }}'>Delete</a>
							</div>
						{% endif %}
					{% endfor %}
			</div>
			<div class="col-md-4">			
				<h2>Football</h2>
					{% for i in players %}
						{% if i.sport == 'Football' %}
						<div class="player-item">
							<h3>{{i.name}}</h3>
							<p>{{i.height}} cm</p>
							<p>{{i.weight}} kg</p>
							<a href='{{url_for('player_url.edit_player', city_id = city.id, player_id=i.id ) }}'>Edit</a> |
							<a href='{{url_for('player_url.delete_player', city_id = city.id, player_id=i.id ) }}'>Delete</a>
						</div>
						{% endif %}
					{% endfor %}
			</div>
			<div class="col-md-3">
				<h2>Hockey</h2>
					{% for i in players %}
						{% if i.sport == 'Hockey' %}
						<div class="player-item">
							<h3>{{i.name}}</h3>
							<p>{{i.height}} cm </p>
							<p>{{i.weight}} kg</p>
							<a href='{{url_for('player_url.edit_player', city_id = city.id, player_id=i.id ) }}'>Edit</a> |
							<a href='{{url_for('player_url.delete_player', city_id = city.id, player_id=i.id ) }}'>Delete</a>
						</div>
						{% endif %}
					{% endfor %}
			</div>
			<div class="col-md-1"></div>
		</div>
	{% endif %}
{% endblock %}

templates/public_cities.html
{% extends "main.html" %}
{% block content %}
	<div class="row top-menu">
		<div class="col-md-10"></div>
		<div class="col-md-2 text-right">
			<a href="{{url_for('user_url.show_login')}}">Click Here to Log in </a>
		</div>
	</div>
	<div class="row divider blue">
		<div class="col-md-12"></div>
	</div>
	<div class="row banner main">
		<div class="col-md-1"></div>
		<div class="col-md-11 padding-none">
			<h1>Cities</h1>
		</div>
	</div>

	<div class = 'flash'>
		      {% with messages = get_flashed_messages() %}
      {% if messages %}
          
        <ul>
        {% for message in messages %}
            <li> <strong> {{ message }} </strong> </li>
        {% endfor %}
        </ul>
        {% endif %}
    {% endwith %}

</div>


	
	<div class="row padding-top padding-bottom">
		<div class="col-md-1"></div>
		<div class="col-md-10 padding-none">
			
		</div>
		<div class="col-md-1"></div>
	</div>
	{% for city in cities %}
		<a href = "{{url_for('player_url.show_players', city_id = city.id)}}">
			<div class="row">
				<div class="col-md-1"></div>
					<div class="col-md-10 city-list">
						<h3>{{city.name}}</h3>
					</div>
				<div class="col-md-1"></div>
			</div>
		</a>
	{% endfor %}
{% endblock %}

templates/public_players.html
{% extends "main.html" %}
{% block content %}
{% include "header.html" %}
	
	<div class="row divider green">
		<div class="col-md-12"></div>
	</div>
	<div class="row padding-top padding-bottom">
		<div class="col-md-1"></div>
		<div class="col-md-11 padding-none">
			
		</div>
		<div class="col-md-7"></div>
	</div>
	<div class="row">
		<div class="col-md-12">
			{% with messages = get_flashed_messages() %}
				{% if messages %}
					<ul>
						{% for message in messages %}
							 <li> <strong> {{ message }} </strong> </li>
						{% endfor %}
					</ul>
				{% endif %}
			{% endwith %}
		</div>
	</div>
	{% if players !=[] %}
		<div class="row">
			<div class="col-md-1"></div>
			<div class="col-md-3">
				<h2>Basketball</h2>
					{% for i in players %}
						{% if i.sport == 'Basketball' %}
							<div class="player-item">
								<h3>{{i.name}}</h3>
								<p>{{i.height}} cm</p>
								<p>{{i.weight}} kg</p>
								<a href='{{url_for('player_url.edit_player', city_id = city.id, player_id=i.id ) }}'>Edit</a> |
								<a href='{{url_for('player_url.delete_player', city_id = city.id, player_id=i.id ) }}'>Delete</a>
							</div>
						{% endif %}
					{% endfor %}
			</div>
			<div class="col-md-4">
				<h2>Football</h2>
					{% for i in players %}
						{% if i.sport == 'Football' %}
						<div class="player-item">
							<h3>{{i.name}}</h3>
							<p>{{i.height}} cm</p>
							<p>{{i.weight}} kg</p>
							<a href='{{url_for('player_url.edit_player', city_id = city.id, player_id=i.id ) }}'>Edit</a> |
							<a href='{{url_for('player_url.delete_player', city_id = city.id, player_id=i.id ) }}'>Delete</a>
						</div>
						{% endif %}
					{% endfor %}
			</div>
			<div class="col-md-3">
				<h2>Hockey</h2>
					{% for i in players %}
						{% if i.sport == 'Hockey' %}
						<div class="player-item">
							<h3>{{i.name}}</h3>
							<p>{{i.height}} cm </p>
							<p>{{i.weight}} kg</p>
							<a href='{{url_for('player_url.edit_player', city_id = city.id, player_id=i.id ) }}'>Edit</a> |
							<a href='{{url_for('player_url.delete_player', city_id = city.id, player_id=i.id ) }}'>Delete</a>
						</div>
						{% endif %}
					{% endfor %}
			</div>
			<div class="col-md-1"></div>
		</div>
	{% endif %}
{% endblock %}